# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui/main_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(767, 555)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 491, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.test = QtWidgets.QCommandLinkButton(self.gridLayoutWidget)
        self.test.setObjectName("test")
        self.gridLayout.addWidget(self.test, 0, 0, 1, 1)
        self.here = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.here.setObjectName("here")
        self.gridLayout.addWidget(self.here, 1, 0, 1, 1)
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(250, 280, 75, 23))
        self.ok.setObjectName("ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.test.setText(_translate("Dialog", "test"))
        self.here.setText(_translate("Dialog", "Here"))
        self.ok.setText(_translate("Dialog", "OK"))
